name: Auto Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    if: github.repository == 'XueMoMo/eericxu_github_app'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4